### ISSUE TITLE
前台 - 邀请好友 是否显示不正确，继续邀请 识别二维码 无法识别 

### ISSUE THREAD

**Issue by yufei1211** [hzcsTeam/fund#122]
![image](https://user-images.githubusercontent.com/31200693/33703596-c524a44e-db63-11e7-9882-0efe603d2e44.png)
# 有空置页面 invite-empty.html

![image](https://user-images.githubusercontent.com/24238082/33747873-607f687e-dc00-11e7-8248-025978672385.png)

**Comment by yezizi** [comment]
# 有空置页面 invite-empty.html

![image](https://user-images.githubusercontent.com/24238082/33747873-607f687e-dc00-11e7-8248-025978672385.png)
