### ISSUE TITLE
文章广告图管理

### ISSUE THREAD

**Issue by WangDong-123** [hzcsTeam/fund#133]
![tim 20171208113526](https://user-images.githubusercontent.com/31264647/33750020-1e41ee1c-dc0c-11e7-9295-430d5cf1b4ce.png)

![tim 20171208113646](https://user-images.githubusercontent.com/31264647/33750026-290b95b4-dc0c-11e7-88fb-fc9df47d9e40.png)

**Comment by keith-hou** [comment]
已修复
