### ISSUE TITLE
前端-轮播图-顺序不对

### ISSUE THREAD

**Issue by yezizi** [hzcsTeam/fund#162]
![image](https://user-images.githubusercontent.com/24238082/33971697-cb9bad26-e0b4-11e7-807d-edee78498f8a.png)
![image](https://user-images.githubusercontent.com/24238082/33971761-228d567a-e0b5-11e7-8bb5-19851a5f06de.png)
![image](https://user-images.githubusercontent.com/24238082/33971791-409298c4-e0b5-11e7-9aea-50d7a37cb068.png)
![image](https://user-images.githubusercontent.com/24238082/33971775-31294310-e0b5-11e7-9529-ecc971104688.png)

**Comment by keith-hou** [comment]
已修改
