### ISSUE TITLE
个人中心-募捐记录（跳两次列表页）

### ISSUE THREAD

**Issue by yezizi** [hzcsTeam/fund#174]
![image](https://user-images.githubusercontent.com/24238082/33981660-b2ed6ce0-e0e8-11e7-8df2-4e827bec3ad6.png)

![image](https://user-images.githubusercontent.com/24238082/33981631-986790ee-e0e8-11e7-9ab5-07e187f07dbd.png)

**Comment by yooqin** [comment]
标记已下架
