### ISSUE TITLE
基金管理-编辑-基金状态

### ISSUE THREAD

**Issue by cailing222** [hzcsTeam/fund#178]
# 描述：基金管理-编辑-基金状态 募捐中改为投资
![qq 20171214170419](https://user-images.githubusercontent.com/31264708/33983981-02f9cc3a-e0f1-11e7-8400-5697f941da53.png)
中

**Comment by cailing222** [comment]
是招标中，不是投资中

**Comment by keith-hou** [comment]
已修改
