### ISSUE TITLE
基金产品模块

### ISSUE THREAD

**Issue by cailing222** [hzcsTeam/fund#19]
# 描述：输入基金名,点击“查询”未显示搜索结果列表；
![qq 20171203155825](https://user-images.githubusercontent.com/31264708/33523457-fb1f5928-d842-11e7-9d37-cb3224f9e4e6.png)

**Comment by cailing222** [comment]
# 若没有搜索结果，未显示空置状态的搜索结果列表页；

**Comment by keith-hou** [comment]
已修改
