### ISSUE TITLE
基金产品-编辑管理

### ISSUE THREAD

**Issue by cailing222** [hzcsTeam/fund#31]
# 描述：基金产品-编辑管理页面数据格式数字型，以元为单位，输入框后面有换算成以万为单位的提醒未实现；
![qq 20171203174543](https://user-images.githubusercontent.com/31264708/33524154-5046f780-d852-11e7-8ee9-992cfaa73912.png)

**Comment by keith-hou** [comment]
问题相同，先关闭了
