### ISSUE TITLE
基金管理-基金编辑-信息详情-起投金额

### ISSUE THREAD

**Issue by cailing222** [hzcsTeam/fund#33]
# 描述：基金管理-基金编辑-信息详情-起投金额 数据格式数字型，以元为单位，输入框后面有换算成以万为单位的提醒未实现；
![qq 20171203182547](https://user-images.githubusercontent.com/31264708/33524450-89c8f804-d858-11e7-93a6-33d018bde288.png)

**Comment by keith-hou** [comment]
已解决
