### ISSUE TITLE
青鸟基金-开关按钮

### ISSUE THREAD

**Issue by yezizi** [hzcsTeam/fund#35]
![image](https://user-images.githubusercontent.com/24238082/33533800-5c6b1c76-d8de-11e7-8856-ece3ca0fc1e3.png)

![image](https://user-images.githubusercontent.com/24238082/33533721-ef7af49c-d8dd-11e7-9e60-b7b27d0d0b95.png)

**Comment by keith-hou** [comment]
已解决
