### ISSUE TITLE
基金产品模块-新建基金并完善页面

### ISSUE THREAD

**Issue by cailing222** [hzcsTeam/fund#40]
描述：基金产品模块-新建基金并完善页面 借款对象为控制字数，字数大于10，不能在输入内容
![qq 20171204111953](https://user-images.githubusercontent.com/31264708/33534920-7299b046-d8e5-11e7-899d-7843e14767ca.png)

**Comment by keith-hou** [comment]
这个最多支持30个字符，10个太少
