### ISSUE TITLE
积分管理-积分统计-积分变更

### ISSUE THREAD

**Issue by yezizi** [hzcsTeam/fund#45]
# 提示语不恰当
![image](https://user-images.githubusercontent.com/24238082/33537538-d6c43c4c-d8f6-11e7-8ebf-b21817e86863.png)
![image](https://user-images.githubusercontent.com/24238082/33537395-45ae830c-d8f6-11e7-831d-36edc7e3ff4a.png)

**Comment by yufei1211** [comment]
已调整
