### ISSUE TITLE
基金产品-新建提交完善页面-提交审核按钮

### ISSUE THREAD

**Issue by cailing222** [hzcsTeam/fund#51]
# 描述：基金产品-新建提交完善页面-提交审核按钮点击出错，
![qq 20171204141418](https://user-images.githubusercontent.com/31264708/33538789-34eb5cc2-d8fe-11e7-819d-7501ceeb66d2.png)

**Comment by keith-hou** [comment]
这个就是保存数据按钮，不是提交按钮
