### ISSUE TITLE
基金产品-用户咨询-返回列表

### ISSUE THREAD

**Issue by cailing222** [hzcsTeam/fund#62]
描述：基金产品-用户咨询-返回列表出错，只输入一个查询条件，点击查询出错，输入不存在查询条件，点击查询没空数据页面
![qq 20171204152825](https://user-images.githubusercontent.com/31264708/33540910-08964e5c-d908-11e7-9bae-7f5feca80ede.png)

**Comment by keith-hou** [comment]
已修改
