### ISSUE TITLE
基金产品列表模块

### ISSUE THREAD

**Issue by cailing222** [hzcsTeam/fund#72]
# 描述：基金产品列表模块的基金负责人和新建基金的基本信息的负责人不一致

![qq 20171204163946](https://user-images.githubusercontent.com/31264708/33543552-6c9999e0-d912-11e7-8ce9-80e591b85c6c.png)
![qq 20171204164041](https://user-images.githubusercontent.com/31264708/33543557-72b7e246-d912-11e7-9e92-1a38affc4bc0.png)

**Comment by keith-hou** [comment]
已解决
