### ISSUE TITLE
基金产品-新建页面-信息详情

### ISSUE THREAD

**Issue by cailing222** [hzcsTeam/fund#75]
# 描述：基金产品-新建页面-信息详情页面 保存按钮点击一次不能点击成功，托管人名微控制字数
![qq 20171204165657](https://user-images.githubusercontent.com/31264708/33544150-936e25a2-d914-11e7-9384-a138c6ab07c9.png)

**Comment by keith-hou** [comment]
已解决，最大支持30个字符
