### ISSUE TITLE
基金产品列表-订单按钮

### ISSUE THREAD

**Issue by cailing222** [hzcsTeam/fund#76]
# 描述：基金产品列表-订单按钮 点击添加订单按钮，弹窗显示应为添加订单弹窗， 点击确定按钮页面不应闪跳

![qq 20171204170656](https://user-images.githubusercontent.com/31264708/33544544-2448527c-d916-11e7-8624-2b4c05bdd9c1.png)

**Comment by keith-hou** [comment]
已完成
