### ISSUE TITLE
订单管理-新建

### ISSUE THREAD

**Issue by cailing222** [hzcsTeam/fund#79]
# 描述：订单管理-新建页面 输入联系人手机号不该提示显示手机号不存在，订单列表页面真实姓名和手机号不应该都显示一样
![qq 20171204180705](https://user-images.githubusercontent.com/31264708/33547229-5fc98f70-d91e-11e7-91f0-9ddce09e3fd5.png)

**Comment by keith-hou** [comment]
已解决
