### ISSUE TITLE
文章管理-审核，募捐管理-审核

### ISSUE THREAD

**Issue by yezizi** [hzcsTeam/fund#87]
四种状态能否一致
![image](https://user-images.githubusercontent.com/24238082/33598604-5c93cfe4-d9de-11e7-964d-085f50d07006.png)
![image](https://user-images.githubusercontent.com/24238082/33598406-9226ba6e-d9dd-11e7-8dd8-d3dec89e2ed8.png)

**Comment by keith-hou** [comment]
已修改
